In [1]:
import sys
import numpy as np

In [2]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[1:-2]

array([2])

In [10]:
a[::2]

array([1, 3])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0,2,-1]]

array([0., 1., 2.])

array types

In [13]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [19]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [20]:
c = np.array(['a','b','c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a','b','c'}])

In [23]:
d.dtype

dtype('O')

dimensions and shapes

In [24]:
A = np.array([
    [1,2,3,4],
    [4,6,7,8]
])

In [25]:
A.shape

(2, 4)

In [26]:
A.size

8

In [27]:
B = np.array([
    [
        [12,21,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [29]:
B.size

12

index and slicing matrices

In [30]:
# square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [31]:
A[1]

array([4, 5, 6])

In [32]:
A[1][0]

4

In [33]:
A[1,0]

4

In [34]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
A[1] = np.array([10,10,10])

In [39]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
A[1] = 99

In [41]:
A

array([[ 1,  2,  3],
       [99, 99, 99],
       [ 7,  8,  9]])

summary statistics

In [42]:
a = np.array([2,7,12,4])

In [43]:
a.sum()

25

In [44]:
a.mean()

6.25

In [45]:
a.std()

3.766629793329841

In [46]:
a.var()

14.1875

In [47]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [48]:
A.sum()

78

In [49]:
a.mean()

6.25

In [50]:
A.mean()

6.5

In [51]:
A.std()

3.452052529534663

In [52]:
A.sum(axis=0)

array([15, 18, 21, 24])

In [53]:
A.sum(axis=1)

array([10, 26, 42])

In [54]:
A.mean(axis=0)

array([5., 6., 7., 8.])

Broadcasting and vectorized operations

In [55]:
a = np.arange(4)

In [56]:
a

array([0, 1, 2, 3])

In [57]:
a + 10

array([10, 11, 12, 13])

In [58]:
a * 10

array([ 0, 10, 20, 30])

In [59]:
a

array([0, 1, 2, 3])

In [64]:
a += 100

In [61]:
a

array([100, 101, 102, 103])

In [62]:
t = [0,1,2,3]

In [66]:
[i * 10 for i in t]

[0, 10, 20, 30]

In [67]:
a = np.arange(4)

In [69]:
b = np.array([10,10,10,10])

In [70]:
a+b

array([10, 11, 12, 13])

In [71]:
a * b

array([ 0, 10, 20, 30])

numpy booleans

In [72]:
a = np.arange(5)

In [73]:
a

array([0, 1, 2, 3, 4])

In [74]:
a[[0, -1]]

array([0, 4])

In [75]:
a >= 2

array([False, False,  True,  True,  True])

In [76]:
a.mean()

2.0

In [78]:
a[a > a.mean()]

array([3, 4])

In [79]:
a[~(a > a.mean())]

array([0, 1, 2])

In [81]:
a[(a==0) | (a==1)]

array([0, 1])

In [82]:
a[(a<=2) & (a % 2 ==0)]

array([0, 2])

In [83]:
A = np.random.randint(100, size=(3,3))

In [84]:
A

array([[52, 97, 32],
       [69, 93, 94],
       [38, 87, 33]])

In [85]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [86]:
A[A > 30]

array([52, 97, 32, 69, 93, 94, 38, 87, 33])

Algebra and Size 

Linear Algebra

In [87]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [88]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [89]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [90]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [91]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [92]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of Objects in Memory

In [94]:
sys.getsizeof(1)

28

In [95]:
sys.getsizeof(10**100)

72

Pandas